project_id = "sdqglyrirchmnpxoyayb"

[functions.create-vip-checkout]
verify_jwt = false

[functions.check-vip-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.fulfill-purchase]
verify_jwt = false
